services:
  address-api:
    image: postgres
    container_name: address-api-db
    environment:
      - POSTGRES_PASSWORD=pg1234
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=address-api-db
    ports:
      - 5432:5432

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - 6379:6379